swagger: '2.0'
info:
  description: Expense Api
  version: 2.0.0
  title: Expense API
  contact:
    email: dipjyotimetia@gmail.com
host: localhost:3001
tags:
  - name: expenses
    description: Expense details  
schemes:
  - http
paths:
  /api/expenses:
    post:
      tags:
        - expenses
      summary: Add expense details
      description: Adds an item to the system
      operationId: addExpenses
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: ExpenseItem
          description: Expense item to add
          required: false
          schema:
            $ref: '#/definitions/ExpenseItem'
      responses:
        '201':
          description: expense details added
        '400':
          description: 'invalid input details'
    get:
      tags:
        - expenses
      summary: Get All Expenses
      description: |
        Get all the expenses
      operationId: getAllExpenses
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: get all expense details
        '400':
          description: bad input parameter
  /api/expenses/{expenseId}:
    put:
      tags:
        - expenses
      summary: Update expense
      description: Update existing expenses
      operationId: updateExpenses
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: expenseId
          description: Expense id
          type: integer
        - in: body
          name: ExpenseItem
          description: Expense item to update
          required: false
          schema:
            $ref: '#/definitions/ExpenseItem'
      responses:
        '201':
          description: expense updated
        '400':
          description: 'invalid data provided'    
  /api/expenses/{username}:
    get:
      tags:
        - expenses
      summary: Get expense by username
      description: Get an expense by username
      operationId: getExpense
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: username
          description: Username
          type: string 
      responses:
        '201':
          description: get expense by user
        '400':
          description: 'Data not found'
  /api/expenses/{id}:
    delete:
      tags:
        - expenses
      summary: Delete Expenses
      description: |
        Delete expenses
      operationId: deleteExpenses
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: Id
          type: integer
      responses:
        '200':
          description: deleted expense details
        '400':
          description: 'expense details not found'
    
definitions:
  ExpenseItem:
    type: object
    required:
      - username
      - expenseType
      - expenseAmount
      - expenseDate
    properties:
      username:
        type: string
        example: username
      expenseType:
        type: string
        example: shopping
      expenseAmount:
        type: integer
        example: 20
      expenseDate:
        type: string
        example: 18/03/2021