version: "3.7"
services:
  backend:
    container_name: accountapi
    restart: always
    build: .
    ports:
      - "3002:3002"
    links:
      - mongodbaccount
  mongodbaccount:
    container_name: mongodbaccount
    environment:
      - MONGO_INITDB_DATABASE=accounts
      # - MONGO_INITDB_ROOT_USERNAME=test
      # - MONGO_INITDB_ROOT_PASSWORD=xyzabc
    image: mongo:3.6.21
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"
